### ISSUE TITLE
docs or book? to_raise vs to_return

### ISSUE THREAD

**Issue by maelle** [ropensci/webmockr#100]
In https://github.com/ropensci/ropenaq/pull/51 I used to use `to_raise()` but I didn't want the `retry()` to actually fail, just to have a 429 HTTP status so I switched to `to_return()`. I'm still not sure whether it's right but I'm sure a docs topic somewhere about "so you want to mock something related to an HTTP error, should you use to_raise() or to_return()" would be great :wink:

**Comment by sckott** [comment]
Thanks for this @maelle - I was just thinking about this the other day.  The reference point I always look at is the Ruby webmock library, as you know. With `to_raise()`, they raise an error rather than simply returning whatever error class is given to `to_raise()` - and thats what we do here.

i don't think we have to follow what webmock library does though. so i've been wondering if we change `to_raise` to not fail, BUT maybe we just document that if you don't want a failure use `to_return(status = 429)` rather than `to_raise(fauxpas::HTTPTooManyRequests)` ?

**Comment by maelle** [comment]
Yes, but the docs should also state _why_/_for what use case_ you'd need either of the behaviors?

**Comment by sckott** [comment]
yes, agree, sounds good
